import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import CustomButton from '../components/CustomButton';

export default function PDFPreview({ navigation }: any) {
  return (
    <View style={styles.container}>
      <Text style={styles.headerTitle}>PDF Preview</Text>

      <View style={styles.pdfCard}>
        <Text style={styles.pdfIcon}>📄</Text>
        <Text style={styles.pdfTitle}>NPS Report — Q2 2026</Text>
        <Text style={styles.pdfMeta}>12 pages · Generated by AI</Text>
      </View>

      <View style={styles.btnRow}>
        <CustomButton
          title="Edit sections"
          onPress={() => {}}
          variant="secondary"
          style={styles.subBtn}
        />
        <CustomButton
          title="Export"
          onPress={() => navigation.navigate('ReportDownload')}
          variant="primary"
          style={styles.subBtn}
        />
      </View>

      <CustomButton
        title="Email PDF Report"
        onPress={() => navigation.navigate('ReportEmail')}
        variant="soft"
        style={styles.emailBtn}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 20,
    paddingTop: 50,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 30,
  },
  pdfCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  pdfIcon: {
    fontSize: 54,
    color: '#8B5CF6',
  },
  pdfTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 16,
  },
  pdfMeta: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 6,
    fontWeight: '500',
  },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  subBtn: {
    flex: 1,
    marginHorizontal: 4,
  },
  emailBtn: {
    marginTop: 10,
    width: '100%',
  },
});
