import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import CustomButton from '../components/CustomButton';
import { brandColors } from '../theme/colors';

export default function Recommendations() {
  const recommendations = [
    'Add a progress indicator to reduce abandonment',
    'Send reminder emails to non-respondents on day 3',
    'Enable anonymous mode for sensitive feedback',
  ];

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.headerTitle}>Recommendations</Text>
      <Text style={styles.subtitle}>
        Personalized action steps generated by AI based on your survey performance metrics.
      </Text>

      {recommendations.map((rec, idx) => (
        <View key={idx} style={styles.recCard}>
          <View style={styles.checkCircle}>
            <Text style={styles.checkSymbol}>✓</Text>
          </View>
          <Text style={styles.recText}>{rec}</Text>
        </View>
      ))}

      <CustomButton
        title="Apply all suggestions"
        onPress={() => alert('Suggestions applied successfully!')}
        variant="primary"
        style={styles.btn}
      />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 30,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 20,
    marginBottom: 24,
  },
  recCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 6,
  },
  checkCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: brandColors.mint,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  checkSymbol: {
    fontSize: 14,
    fontWeight: '700',
    color: '#047857',
  },
  recText: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '600',
    lineHeight: 18,
  },
  btn: {
    marginTop: 24,
    width: '100%',
  },
});
