/**
 * pages/ai/AIQuestionGenerator.jsx
 * Production AI generator with context fields (audience + goal + count),
 * professional source indicators, Framer Motion, dark mode, and real OpenAI integration.
 */
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import toast from 'react-hot-toast'
import { generateQuestions, saveSurvey } from '../../services/api'
import Button from '../../components/ui/Button'
import Input  from '../../components/ui/Input'
import { Skeleton } from '../../components/ui/Skeleton'

const TYPE_ICON  = { mcq: '🔘', text: '✏️', rating: '⭐', checkbox: '☑️', dropdown: '🔽' }
const TYPE_LABEL = { mcq: 'Multiple Choice', text: 'Open Text', rating: 'Rating', checkbox: 'Checkbox', dropdown: 'Dropdown' }
const TYPE_COLOR = {
  mcq:      'chip-pastel chip-lavender',
  text:     'chip-pastel chip-peach',
  rating:   'chip-pastel chip-pink',
  checkbox: 'chip-pastel chip-mint',
  dropdown: 'chip-pastel chip-cyan',
}

const QUICK_TOPICS = [
  'Customer Support Experience',
  'Employee Engagement & Wellbeing',
  'Product Usability Feedback',
  'Event & Conference Experience',
  'Remote Work & Collaboration',
  'Brand Perception & Awareness',
]

const AUDIENCE_OPTIONS = [
  '', 'Existing customers', 'New customers', 'Prospects / leads',
  'Employees', 'Managers / leaders', 'Event attendees',
  'Beta testers', 'General public',
]

const GOAL_OPTIONS = [
  '', 'Measure overall satisfaction (CSAT)',
  'Calculate Net Promoter Score (NPS)',
  'Identify key pain points and friction',
  'Prioritize product features',
  'Evaluate a recent event or campaign',
  'Assess employee sentiment',
  'Collect open-ended feedback',
  'Benchmark against a previous period',
]

const container = { hidden: {}, show: { transition: { staggerChildren: 0.05 } } }
const cardItem  = { hidden: { opacity: 0, x: -12 }, show: { opacity: 1, x: 0, transition: { duration: 0.22 } } }

export default function AIQuestionGenerator() {
  const navigate = useNavigate()
  const [topic,     setTopic]    = useState('')
  const [audience,  setAudience] = useState('')
  const [goal,      setGoal]     = useState('')
  const [count,     setCount]    = useState(8)
  const [questions, setQs]       = useState([])
  const [loading,   setLoading]  = useState(false)
  const [saving,    setSaving]   = useState(false)
  const [editingId, setEditingId]= useState(null)
  const [source,    setSource]   = useState(null) // 'openai' | 'template'

  const generate = async () => {
    if (!topic.trim()) { toast.error('Please enter a survey topic first'); return }
    setLoading(true)
    setQs([])
    const toastId = toast.loading('✨ Generating professional questions…')
    try {
      const data = await generateQuestions(topic.trim(), count, audience, goal)
      const qs   = data.questions ?? data
      setQs(qs)
      setSource(data.source ?? 'ai')
      toast.success(`✅ ${qs.length} professional questions generated by ${(data.source || 'AI').toUpperCase()}`, { id: toastId })
    } catch (err) {
      const msg = err.response?.data?.error ?? err.message
      toast.error(msg, { id: toastId, duration: 6000 })
      setSource(null)
    } finally {
      setLoading(false)
    }
  }

  const deleteQ    = (id)        => setQs((p) => p.filter((q) => q.id !== id))
  const updateQ    = (id, text)  => setQs((p) => p.map((q) => q.id === id ? { ...q, text } : q))
  const toggleType = (id) => {
    const types = ['mcq', 'text', 'rating', 'checkbox', 'dropdown']
    setQs((p) => p.map((q) => {
      if (q.id !== id) return q
      const next = types[(types.indexOf(q.type) + 1) % types.length]
      return { ...q, type: next }
    }))
  }

  const handleSaveToBuilder = async () => {
    if (!topic.trim()) { toast.error('Please enter a topic first'); return }
    setSaving(true)
    const toastId = toast.loading('Saving survey…')
    try {
      const res = await saveSurvey({ title: topic.trim(), description: goal || '', questions })
      toast.success('Survey saved! Opening builder…', { id: toastId })
      setTimeout(() => navigate(`/surveys/builder/${res.data?.id}`), 800)
    } catch (err) {
      toast.error('Could not save: ' + (err.response?.data?.error ?? err.message), { id: toastId })
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="max-w-3xl mx-auto space-y-8">

      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}>
        <div className="badge badge-ai mb-3 uppercase tracking-wider">
          {source ? `Powered by ${source.toUpperCase()}` : 'AI-POWERED SURVEY DESIGN'}
        </div>
        <h2 className="text-3xl font-bold text-[var(--sf-text)] tracking-tight font-display">
          AI Question <span className="gradient-text">Generator</span>
        </h2>
        <p className="text-sm text-[var(--sf-text-secondary)] mt-1.5 font-medium">
          Enter your topic, context, and goals — our AI crafts professional, research-grade survey questions.
        </p>
      </motion.div>

      {/* Input card */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0, transition: { delay: 0.1 } }}
        className="card card-gradient-border p-6 space-y-5">

        {/* Topic */}
        <Input
          id="ai-topic"
          label="Survey Topic *"
          placeholder="e.g. Customer Support Experience, Remote Work Tools…"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && generate()}
          icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
          </svg>}
        />

        {/* Quick topics */}
        <div className="flex flex-wrap gap-2">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-600 w-full uppercase tracking-wide">
            Quick topics:
          </p>
          {QUICK_TOPICS.map((t) => (
            <button key={t} onClick={() => setTopic(t)}
              className={`px-3 py-1.5 text-xs font-semibold rounded-full transition-all
                border border-primary-200 dark:border-primary-800
                ${topic === t
                  ? 'bg-primary-500 text-white border-primary-500'
                  : 'bg-primary-50 dark:bg-primary-500/10 text-primary-600 dark:text-primary-400 hover:bg-primary-100 dark:hover:bg-primary-500/20'}`}
            >
              {t}
            </button>
          ))}
        </div>

        {/* Context fields — two columns */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1 border-t border-gray-100 dark:border-[#1e1e2e]">
          <div>
            <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
              Target Audience <span className="text-gray-400 font-normal">(optional)</span>
            </label>
            <select
              value={audience}
              onChange={(e) => setAudience(e.target.value)}
              className="w-full px-4 py-2.5 border border-gray-200 dark:border-[#2a2a3a] rounded-xl text-sm
                         bg-white dark:bg-[#13131a] text-gray-700 dark:text-gray-300
                         focus:outline-none focus:ring-2 focus:ring-primary-400"
            >
              {AUDIENCE_OPTIONS.map((o) => (
                <option key={o} value={o}>{o || 'Select audience…'}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
              Survey Goal <span className="text-gray-400 font-normal">(optional)</span>
            </label>
            <select
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              className="w-full px-4 py-2.5 border border-gray-200 dark:border-[#2a2a3a] rounded-xl text-sm
                         bg-white dark:bg-[#13131a] text-gray-700 dark:text-gray-300
                         focus:outline-none focus:ring-2 focus:ring-primary-400"
            >
              {GOAL_OPTIONS.map((o) => (
                <option key={o} value={o}>{o || 'Select goal…'}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Question count slider */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-sm font-semibold text-gray-700 dark:text-gray-300">
              Number of Questions
            </label>
            <span className="text-sm font-bold text-primary-600 dark:text-primary-400 bg-primary-50 dark:bg-primary-500/20 px-3 py-1 rounded-full">
              {count}
            </span>
          </div>
          <input
            type="range" min={4} max={15} step={1}
            value={count}
            onChange={(e) => setCount(Number(e.target.value))}
            className="w-full accent-primary-500"
          />
          <div className="flex justify-between text-xs text-gray-400 dark:text-gray-600 mt-1">
            <span>4 (focused)</span>
            <span>10 (standard)</span>
            <span>15 (comprehensive)</span>
          </div>
        </div>

        <Button onClick={generate} loading={loading} size="lg" fullWidth>
          {loading ? 'Generating…' : '✨ Generate Professional Questions'}
        </Button>

      </motion.div>

      {/* Loading skeleton */}
      {loading && (
        <div className="space-y-3">
          {Array(count > 6 ? 6 : count).fill(0).map((_, i) => (
            <div key={i} className="card p-5 flex items-start gap-4">
              <Skeleton className="w-8 h-8 rounded-xl shrink-0" />
              <div className="flex-1 space-y-2">
                <Skeleton className="h-3.5 w-24 rounded-full" />
                <Skeleton className="h-4 w-4/5" />
                <Skeleton className="h-3.5 w-3/5" />
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Generated questions */}
      <AnimatePresence>
        {questions.length > 0 && !loading && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">

            {/* Action bar */}
            <div className="flex items-center justify-between flex-wrap gap-3">
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="font-bold text-gray-800 dark:text-gray-100">
                  {questions.length} Questions Generated
                </h3>
                <span className="badge bg-primary-100 dark:bg-primary-500/20 text-primary-600 dark:text-primary-400">
                  {topic}
                </span>
                {source && (
                  <span className="badge bg-green-100 dark:bg-green-500/20 text-green-700 dark:text-green-400">
                    ✅ Generated with {source.toUpperCase()}
                  </span>
                )}
              </div>
              <div className="flex gap-2">
                <Button variant="secondary" size="sm" onClick={generate} loading={loading}>
                  ↻ Regenerate
                </Button>
                <Button size="sm" onClick={handleSaveToBuilder} loading={saving}>
                  → Save to Builder
                </Button>
              </div>
            </div>

            {/* Type distribution summary */}
            {(() => {
              const dist = questions.reduce((acc, q) => { acc[q.type] = (acc[q.type] || 0) + 1; return acc }, {})
              return (
                <div className="flex flex-wrap gap-2 px-1">
                  {Object.entries(dist).map(([type, n]) => (
                    <span key={type} className={`text-xs font-semibold px-2.5 py-1 rounded-full ${TYPE_COLOR[type] ?? ''}`}>
                      {TYPE_ICON[type]} {n} {TYPE_LABEL[type]}
                    </span>
                  ))}
                </div>
              )
            })()}

            {/* Question cards */}
            <motion.div variants={container} initial="hidden" animate="show" className="space-y-3">
              {questions.map((q, idx) => (
                <motion.div
                  key={q.id}
                  variants={cardItem}
                  layout
                  className="card card-gradient-border p-5 flex items-start gap-4 group card-hover"
                >
                  <div className="w-8 h-8 rounded-xl bg-[var(--pastel-lavender)]
                    flex items-center justify-center text-xs font-bold text-[#0f172a] shrink-0 shadow-sm">
                    {idx + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2">
                      <button
                        onClick={() => toggleType(q.id)}
                        title="Click to change type"
                        className={`badge cursor-pointer hover:opacity-80 transition-opacity ${TYPE_COLOR[q.type] ?? TYPE_COLOR.text}`}
                      >
                        {TYPE_ICON[q.type]} {TYPE_LABEL[q.type] ?? q.type}
                      </button>
                    </div>

                    {editingId === q.id ? (
                      <textarea
                        autoFocus
                        rows={2}
                        value={q.text}
                        onChange={(e) => updateQ(q.id, e.target.value)}
                        onBlur={() => setEditingId(null)}
                        className="w-full text-sm font-medium text-gray-800 dark:text-gray-200
                          border-b border-primary-400 focus:outline-none bg-transparent pb-0.5 resize-none"
                      />
                    ) : (
                      <p className="text-sm font-medium text-[var(--sf-text)] leading-relaxed">
                        {q.text}
                      </p>
                    )}

                    {/* Show MCQ options preview */}
                    {['mcq', 'checkbox', 'dropdown'].includes(q.type) && q.options?.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {q.options.map((o, oi) => (
                          <span key={oi} className="text-xs chip-pastel chip-cyan">
                            {o}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="flex gap-1 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => setEditingId(q.id)}
                      className="p-1.5 rounded-lg text-gray-400 hover:bg-primary-50 dark:hover:bg-primary-500/10
                        hover:text-primary-500 transition-all" title="Edit">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                          d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
                      </svg>
                    </button>
                    <button onClick={() => { deleteQ(q.id); toast.success('Question removed') }}
                      className="p-1.5 rounded-lg text-gray-400 hover:bg-red-50 dark:hover:bg-red-500/10
                        hover:text-red-500 transition-all" title="Remove">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                          d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                      </svg>
                    </button>
                  </div>
                </motion.div>
              ))}
            </motion.div>

            {/* Bottom CTA */}
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1, transition: { delay: 0.4 } }}
              className="card p-5 flex items-center justify-between gap-4"
              style={{ background: 'linear-gradient(135deg, rgba(214,198,255,0.35), rgba(184,242,245,0.25))' }}>
              <div>
                <p className="font-bold text-primary-700 dark:text-primary-300 text-sm">
                  Ready to publish? Save this survey →
                </p>
                <p className="text-xs text-primary-600 dark:text-primary-400 mt-0.5">
                  Saves to builder where you can reorder questions, edit options, and get a share link.
                </p>
              </div>
              <Button size="sm" onClick={handleSaveToBuilder} loading={saving}>
                Save & Open Builder
              </Button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Empty state */}
      {questions.length === 0 && !loading && (
        <motion.div initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }}
          className="text-center py-20 text-gray-400 dark:text-gray-600">
          <div className="w-20 h-20 bg-primary-50 dark:bg-primary-500/10 rounded-3xl flex items-center justify-center text-4xl mx-auto mb-5">
            🤖
          </div>
          <p className="font-bold text-gray-600 dark:text-gray-400 text-lg">AI ready to generate</p>
          <p className="text-sm mt-1">Enter a topic, configure context, and click Generate</p>
          <div className="mt-4 flex flex-wrap justify-center gap-4 text-xs text-gray-400 dark:text-gray-600">
            <span>✅ Domain-aware questions</span>
            <span>✅ Strategic type mix</span>
            <span>✅ Research-grade quality</span>
            <span>✅ Ready in 2–4 seconds</span>
          </div>
        </motion.div>
      )}
    </div>
  )
}
