const express = require('express')
const router = express.Router()
const { requireAuth } = require('../middleware/auth')
const authController = require('../controllers/authController')

router.post('/signup', authController.signup)
router.post('/verify-otp', authController.verifyOtp)
router.post('/resend-otp', authController.resendOtp)
router.post('/login', authController.login)
router.post('/forgot-password', authController.forgotPassword)
router.post('/reset-password', authController.resetPassword)
router.get('/me', authController.getMe)
router.put('/profile', authController.updateProfile)
router.get('/test-email', authController.testEmail)
router.post('/test-helper/reset-limits', authController.resetLimits)
router.post('/logout', requireAuth, authController.logout)
router.get('/test-helper/latest-otps', authController.getLatestOtps)
router.post('/test-helper/promote-admin', authController.promoteAdmin)

module.exports = router
